### ISSUE TITLE
payment Data required in paymentDetails Request

### ISSUE THREAD

**Issue by abenmoussa** [Adyen/adyen-java-api-library#551] opened 2021-05-17 07:55 UTC
Hello,

**Describe the bug**

After a payment with 3D redirect result, the API did not return the value of paymentData (OK).

> Release Note: "For payment methods with action.type: redirect, the response no longer contains paymentData". 

Then, although in release notes I found this:  

> POST /payments/details For payment methods with action.type: redirect, you no longer need to submit paymentData.

When I wanted to call the payment Details with Java Code, I had this error (Not OK):

_ApiException{error=class ApiError {
    status: 422
    errorCode: 14_002
    message: Required field 'paymentData' is not provided.
    errorType: validation
    pspReference: 861621231797281K
    invalidFields: null
}, statusCode=422, message=HTTP Exception, responseHeaders={Transfer-Encoding=[chunked], Keep-Alive=[timeout=15, max=100], null=[HTTP/1.1 422 422], Server=[Apache], Connection=[Keep-Alive], Set-Cookie=[JSESSIONID=F8D88810B067E023364A0B26B772840B.test8e; Path=/checkout; Secure; HttpOnly], pspReference=[861621231797281K], Date=[Mon, 17 May 2021 06:09:57 GMT], Content-Type=[application/json;charset=UTF-8]}}
	at com.adyen.service.Resource.request(Resource.java:81)
	at com.adyen.service.Checkout.paymentsDetails(Checkout.java:138)
	at com.adyen.service.Checkout.paymentsDetails(Checkout.java:133)_

**How to reproduce**
1- do a payment with a redirect result (3D Security 1).
2 - Validate the payment from the validation page.
3 - Submit details to get the payment status.

**Expected behavior**
I expected to submit only the field details to get the payment status.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Java Version: 8
 - Library Version: 14.0.0

**Comment by Aleffio** [comment] 2021-05-21 12:46
Hi @abenmoussa thanks for opening the issue,
can you please contact support@adyen.com for this request?
It might be a configuration issue, providing them with the PSP reference of the first request might also be helpful.

Regards,
Alessio
Adyen

**Comment by seizmo** [comment] 2021-05-22 23:00
I can confirm this bug. With Alipay as payment method, no paymentData is returned, however the API gives the above mentioned error. Seems to be more of an API issue.

**Comment by AlexandrosMor** [comment] 2021-08-09 09:30
We will close this issue as it is API related and not library

**Closed by AlexandrosMor** 2021-08-09 09:30 UTC
